# Generated by Django 4.2.3 on 2023-07-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
