# Generated by Django 4.2.3 on 2023-10-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
